apiVersion: v1
kind: Service
metadata:
  name: app-tiger
  namespace: sre-prototype
spec:
  selector:
    app: app-tiger
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP